# Generated by Django 3.0.5 on 2020-04-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
    ]
