# Generated by Django 3.0.5 on 2020-04-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.TextField(default='[]')),
            ],
        ),
    ]
